### ISSUE TITLE
Docs: explain how to deal with CORS

### ISSUE THREAD

**Issue by nhoizey** [11ty/api-screenshot#8]
I've installed this on my own domain screenshots.nicolas-hoizey.com hosted on Netlify.

It works well when run in the browser:
https://screenshots.nicolas-hoizey.com/https%3A%2F%2Fcloudfour.com%2Fthinks%2Fsvg-icon-stress-test%2F/large/

But I get a CORS error when I try to use this image in a page on another domain:
![image](https://user-images.githubusercontent.com/78213/139535949-5ac1083c-871b-4da7-bc6b-e74daba34a88.png)

I tried to add this to my `netlify.toml` file, but it doesn't fix the issue:

```toml
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
```

Is there something specific to do because it's a Netlify Function?

There might be something here: https://stackoverflow.com/a/57974136/717195
